
require "json"
require "active_support"

def shell(cmd)
  $stderr.puts cmd
  system cmd
  if not $?.success?
    raise "error exit"
  end
end

desc "build js app vendor libraries"
task "app-vendor" => ["app-vendor.json"] do |t|
  vendor_libs = JSON.parse(File.read("app-vendor.json"))
  requires = vendor_libs.to_a.map { |dep| "-r ./#{dep[1]}:#{dep[0]}" }.join " "
  cmd = "browserify --no-detect-globals #{requires}"
  shell cmd
end

desc "build js app"
task "app" => ["app.coffee","app-vendor.coffee"] do |t|
  vendor_libs = JSON.parse(File.read("app-vendor.json"))
  externals = vendor_libs.to_a.map { |dep| "-x ./#{dep[1]}:#{dep[0]}" }.join " "
  cmd = "browserify  -t coffeeify --extension='.coffee' --no-detect-globals #{externals} app.coffee"
  shell cmd
end

desc "build mobile js app"
task "mobile" => ["mobile.coffee","mobile-vendor.coffee"] do |t|
  vendor_libs = JSON.parse(File.read("mobile-vendor.json"))
  requires = vendor_libs.to_a.map { |dep| "-r ./#{dep[1]}:#{dep[0]}" }.join " "
  cmd = "browserify  -t coffeeify --extension='.coffee' --no-detect-globals #{requires} mobile.coffee"
  shell cmd
end

build = "build"
js_build = "#{build}/js"

rule /^#{js_build}\/.+\.js$/ do |t|
  shell "mkdir -p #{js_build}"
  task = File.basename(t.name,".js")
  shell "rake #{task} > #{t.name} || rm #{t.name}"
end

desc "build all js files"
task "js" => [
  "#{js_build}/app.js",
  "#{js_build}/app-vendor.js",
  "#{js_build}/mobile.js"
]

