require "json"
require "active_support"

def shell(cmd)
  $stderr.puts cmd
  system cmd
  if not $?.success?
    raise "error exit"
  end
end

build = "build"
js_build = "#{build}/js"
css_build = "#{build}/css"
css_src = "src/css"
js_src = "src"
coffee_files = Dir[js_src + "/**/*.coffee"]
hbs_files = Dir[js_src + "/**/*.hbs"]
js_sources = coffee_files + hbs_files

task "build" => ["js","css"]

desc "build all js files"
task "js" => [
  js_build,
  "#{js_build}/app.js",
  "#{js_build}/app-vendor.js",
  "#{js_build}/mobile.js",
]

browserify = "browserify  -t hbsfy -t coffeeify --extension='.coffee' --no-detect-globals"

file "#{js_build}/mobile.js" => ["#{js_src}/mobile-vendor.json",*js_sources] do |t|
  entry = "#{js_src}/mobile.coffee"
  vendor_libs = JSON.parse(File.read("#{js_src}/mobile-vendor.json"))
  requires = vendor_libs.to_a.map { |dep| "-r ./#{dep[1]}:#{dep[0]}" }.join " "
  cmd = "#{browserify} #{requires} #{entry} -o #{t.name}"
  shell cmd rescue  shell "rm #{t.name}"
end

file "#{js_build}/app-vendor.js" => ["#{js_src}/app-vendor.json"] do |t|
  # Too many weird edge cases with different build tools people use, that it's more robust to just cat together the vendor files instead of using browserify.
  # For example, browserify can't require the react.js build.
  vendor_libs = JSON.parse(File.read("#{js_src}/app-vendor.json"))

  # requires = vendor_libs.to_a.map { |dep| "-r ./#{dep[1]}:#{dep[0]}" }.join " "
  srcs = vendor_libs.to_a.map { |dep| dep[1] }.join " "
  cmd = "cat #{srcs} > #{t.name}"
  shell cmd rescue "rm #{t.name}"
end

file "#{js_build}/app.js" => ["#{js_src}/app-vendor.json",*js_sources] do |t|
  p t.prerequisites
  vendor_libs = JSON.parse(File.read("#{js_src}/app-vendor.json"))
  entry = "#{js_src}/app.coffee"
  externals = vendor_libs.to_a.map { |dep| "-x ./#{dep[1]}:#{dep[0]}" }.join " "
  cmd = "#{browserify} #{externals} #{entry} -o #{t.name} --debug"
  shell cmd rescue "rm #{t.name}"
end

task "css" => [
  "#{css_build}/app.css",
  "#{css_build}/mobile.css"
]

js_sources = lambda { |target|
  name = File.basename(target,".js")
  (["#{js_src}/#{name}.coffee"] + Dir[js_src+"/**/*.coffee"]).uniq
}

rule /^#{js_build}\/.+\.js$/ do |t|
  shell "mkdir -p #{js_build}"
  task = File.basename(t.name,".js")
  shell "rake #{task} > #{t.name} || rm #{t.name}"
end

css_source = lambda { |target|
  name = File.basename(target,".css")
  (["#{css_src}/#{name}.less"] + Dir[css_src+"/**/*.less"]).uniq
}

rule /^#{css_build}\/.*css$/ => [css_source] do |t|
  entry = t.prerequisites[0]
  shell "mkdir -p #{css_build}"
  shell "lessc #{entry} #{t.name}"
end
